/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.CustomerMaintenanceControl;
import Model.Invoice;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class PayInvoice extends javax.swing.JFrame {
    
    CustomerMaintenanceControl control;
    Invoice invoice;
    private static SimpleDateFormat dateFormat = new SimpleDateFormat("MM/YYYY");
    /**
     * Creates new form PayInvoice
     */
    public PayInvoice() {
        initComponents();
    }
    
    public PayInvoice(CustomerMaintenanceControl control) {
        this.control = control;
        initComponents();
        jlCustomerId.setVisible(false);
        jlAmount.setVisible(false);
        jlGeneratedDate.setVisible(false);
        jtfCustomerId.setVisible(false);
        jtfAmount.setVisible(false);
        jtfGeneratedDate.setVisible(false);
        jbPay.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlblHeader = new javax.swing.JLabel();
        jlInvoiceNo = new javax.swing.JLabel();
        jtfInvoiceNo = new javax.swing.JTextField();
        jbSearch = new javax.swing.JButton();
        jlCustomerId = new javax.swing.JLabel();
        jlAmount = new javax.swing.JLabel();
        jlGeneratedDate = new javax.swing.JLabel();
        jtfCustomerId = new javax.swing.JTextField();
        jtfAmount = new javax.swing.JTextField();
        jtfGeneratedDate = new javax.swing.JTextField();
        jbPay = new javax.swing.JButton();
        jbClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlblTitle.setForeground(new java.awt.Color(102, 0, 0));
        jlblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitle.setText("Fiore Flowershop");

        jSeparator1.setForeground(new java.awt.Color(153, 0, 51));

        jlblHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblHeader.setForeground(new java.awt.Color(153, 0, 0));
        jlblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblHeader.setText("Customer Maintenance");

        jlInvoiceNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlInvoiceNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlInvoiceNo.setText("Invoice No:");

        jtfInvoiceNo.setToolTipText("eg. I001");

        jbSearch.setText("Search");
        jbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchActionPerformed(evt);
            }
        });

        jlCustomerId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCustomerId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlCustomerId.setText("Customer ID:");

        jlAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlAmount.setText("Amount:");

        jlGeneratedDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlGeneratedDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlGeneratedDate.setText("Generated Date:");

        jtfCustomerId.setEditable(false);
        jtfCustomerId.setToolTipText("eg. I001");

        jtfAmount.setEditable(false);
        jtfAmount.setToolTipText("eg. I001");

        jtfGeneratedDate.setEditable(false);
        jtfGeneratedDate.setToolTipText("eg. I001");

        jbPay.setText("Pay");
        jbPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPayActionPerformed(evt);
            }
        });

        jbClose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbClose.setText("Close");
        jbClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jlblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlGeneratedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlAmount)
                                    .addComponent(jlCustomerId)
                                    .addComponent(jlInvoiceNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbSearch))
                                    .addComponent(jtfCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfGeneratedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbClose, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbPay, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlInvoiceNo)
                                    .addComponent(jtfInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbSearch))
                                .addGap(40, 40, 40)
                                .addComponent(jlCustomerId))
                            .addComponent(jtfCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlAmount))
                    .addComponent(jtfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlGeneratedDate)
                    .addComponent(jtfGeneratedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jbPay)
                .addGap(18, 18, 18)
                .addComponent(jbClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchActionPerformed
        // TODO add your handling code here:
        String invoiceNo = jtfInvoiceNo.getText();
        if(!invoiceNo.equals("")){
            if(control.invoiceNoValidation(invoiceNo)){
                invoice = control.getInvoice(invoiceNo);
                if(invoice != null && !invoice.getIsPaid()){
                    jtfCustomerId.setText(invoice.getCustomer().getCustID());
                    jtfAmount.setText(String.valueOf(invoice.getAmount()));
                    jtfGeneratedDate.setText(dateFormat.format(invoice.getGeneratedDate()));
                    jlCustomerId.setVisible(true);
                    jlAmount.setVisible(true);
                    jlGeneratedDate.setVisible(true);
                    jtfCustomerId.setVisible(true);
                    jtfAmount.setVisible(true);
                    jtfGeneratedDate.setVisible(true);
                    jbPay.setVisible(true);
                
                }
                else if (invoice == null){
                    JOptionPane.showMessageDialog(null, "Record Not found.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "This invoice is paid.", "Error", JOptionPane.ERROR_MESSAGE);

                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Invoice No. Format", "Invalid", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Empty Invoice No.!!!", "Empty", JOptionPane.ERROR_MESSAGE);

        }
        
    }//GEN-LAST:event_jbSearchActionPerformed

    private void jbPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPayActionPerformed
        // TODO add your handling code here:
        if(invoice!=null){
            control.payInvoice(invoice);
            JOptionPane.showMessageDialog(null, "Invoice No." + invoice.getInvoiceNo() + " paid");
            jlCustomerId.setVisible(false);
            jlAmount.setVisible(false);
            jlGeneratedDate.setVisible(false);
            jtfCustomerId.setVisible(false);
            jtfAmount.setVisible(false);
            jtfGeneratedDate.setVisible(false);
            jbPay.setVisible(false);
            invoice = null;
            
        }

    }//GEN-LAST:event_jbPayActionPerformed

    private void jbCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbClose;
    private javax.swing.JButton jbPay;
    private javax.swing.JButton jbSearch;
    private javax.swing.JLabel jlAmount;
    private javax.swing.JLabel jlCustomerId;
    private javax.swing.JLabel jlGeneratedDate;
    private javax.swing.JLabel jlInvoiceNo;
    private javax.swing.JLabel jlblHeader;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JTextField jtfAmount;
    private javax.swing.JTextField jtfCustomerId;
    private javax.swing.JTextField jtfGeneratedDate;
    private javax.swing.JTextField jtfInvoiceNo;
    // End of variables declaration//GEN-END:variables
}
